# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1500, 1004)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(9)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1500, 1000))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1500, 40))
        self.label.setMinimumSize(QtCore.QSize(450, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.main = QtWidgets.QFrame(self.centralwidget)
        self.main.setGeometry(QtCore.QRect(30, 50, 1440, 920))
        self.main.setMinimumSize(QtCore.QSize(1440, 920))
        self.main.setFrameShape(QtWidgets.QFrame.Box)
        self.main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main.setLineWidth(1)
        self.main.setObjectName("main")
        self.Condition = QtWidgets.QFrame(self.main)
        self.Condition.setGeometry(QtCore.QRect(40, 20, 1360, 200))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Condition.sizePolicy().hasHeightForWidth())
        self.Condition.setSizePolicy(sizePolicy)
        self.Condition.setMinimumSize(QtCore.QSize(1360, 150))
        self.Condition.setFrameShape(QtWidgets.QFrame.Panel)
        self.Condition.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Condition.setLineWidth(1)
        self.Condition.setObjectName("Condition")
        self.label_2 = QtWidgets.QLabel(self.Condition)
        self.label_2.setGeometry(QtCore.QRect(40, 10, 1360, 50))
        self.label_2.setMinimumSize(QtCore.QSize(1360, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.Condition)
        self.label_3.setGeometry(QtCore.QRect(20, 55, 141, 131))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.Condition)
        self.label_4.setGeometry(QtCore.QRect(11, 50, 1341, 141))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.Condition)
        self.label_5.setGeometry(QtCore.QRect(1063, 50, 131, 141))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.servo = QtWidgets.QLCDNumber(self.Condition)
        self.servo.setGeometry(QtCore.QRect(780, 90, 111, 51))
        self.servo.setMinimumSize(QtCore.QSize(110, 50))
        self.servo.setObjectName("servo")
        self.battery = QtWidgets.QLCDNumber(self.Condition)
        self.battery.setGeometry(QtCore.QRect(1190, 90, 110, 50))
        self.battery.setMinimumSize(QtCore.QSize(110, 50))
        self.battery.setObjectName("battery")
        self.speed = QtWidgets.QLCDNumber(self.Condition)
        self.speed.setGeometry(QtCore.QRect(150, 90, 110, 50))
        self.speed.setMinimumSize(QtCore.QSize(110, 50))
        self.speed.setObjectName("speed")
        self.autopilot = QtWidgets.QFrame(self.main)
        self.autopilot.setGeometry(QtCore.QRect(40, 240, 1360, 650))
        self.autopilot.setMinimumSize(QtCore.QSize(1360, 650))
        self.autopilot.setFrameShape(QtWidgets.QFrame.Panel)
        self.autopilot.setFrameShadow(QtWidgets.QFrame.Raised)
        self.autopilot.setObjectName("autopilot")
        self.camera_2 = QtWidgets.QFrame(self.autopilot)
        self.camera_2.setGeometry(QtCore.QRect(20, 90, 541, 541))
        self.camera_2.setFrameShape(QtWidgets.QFrame.Box)
        self.camera_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.camera_2.setObjectName("camera_2")
        self.push_button1 = QtWidgets.QPushButton('Connect', self.camera_2)
        self.push_button1.setGeometry(QtCore.QRect(175, 225, 200, 100))
        self.bln = QtWidgets.QPushButton('stop', self.camera_2)
        self.bln.setGeometry(QtCore.QRect(175, 0, 200, 100))
        self.label_6 = QtWidgets.QLabel(self.autopilot)
        self.label_6.setGeometry(QtCore.QRect(40, 10, 1360, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.cruise_control = QtWidgets.QFrame(self.autopilot)
        self.cruise_control.setGeometry(QtCore.QRect(700, 130, 611, 151))
        self.cruise_control.setFrameShape(QtWidgets.QFrame.Box)
        self.cruise_control.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cruise_control.setObjectName("cruise_control")
        self.label_7 = QtWidgets.QLabel(self.cruise_control)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 441, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.speed_input = QtWidgets.QLineEdit(self.cruise_control)
        self.speed_input.setGeometry(QtCore.QRect(170, 100, 151, 31))
        self.speed_input.setObjectName("speed_input")
        self.label_8 = QtWidgets.QLabel(self.cruise_control)
        self.label_8.setGeometry(QtCore.QRect(10, 80, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.cruise = QtWidgets.QCheckBox(self.cruise_control)
        self.cruise.setGeometry(QtCore.QRect(460, 10, 131, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cruise.setFont(font)
        self.cruise.setObjectName("cruise")
        self.collision_prevention = QtWidgets.QFrame(self.autopilot)
        self.collision_prevention.setGeometry(QtCore.QRect(700, 330, 611, 101))
        self.collision_prevention.setFrameShape(QtWidgets.QFrame.Box)
        self.collision_prevention.setFrameShadow(QtWidgets.QFrame.Raised)
        self.collision_prevention.setObjectName("collision_prevention")
        self.label_9 = QtWidgets.QLabel(self.collision_prevention)
        self.label_9.setGeometry(QtCore.QRect(10, 10, 451, 81))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.collision = QtWidgets.QCheckBox(self.collision_prevention)
        self.collision.setGeometry(QtCore.QRect(470, 10, 131, 81))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.collision.setFont(font)
        self.collision.setObjectName("collision")
        self.lane_keeping = QtWidgets.QFrame(self.autopilot)
        self.lane_keeping.setGeometry(QtCore.QRect(700, 490, 611, 101))
        self.lane_keeping.setFrameShape(QtWidgets.QFrame.Box)
        self.lane_keeping.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lane_keeping.setObjectName("lane_keeping")
        self.label_10 = QtWidgets.QLabel(self.lane_keeping)
        self.label_10.setGeometry(QtCore.QRect(20, 10, 441, 81))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.lane = QtWidgets.QCheckBox(self.lane_keeping)
        self.lane.setGeometry(QtCore.QRect(470, 10, 131, 81))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lane.setFont(font)
        self.lane.setObjectName("lane")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1500, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Autopilot Model Car Control System"))
        self.label_2.setText(_translate("MainWindow", "Current Condition"))
        self.label_3.setText(_translate("MainWindow", "Speed:"))
        self.label_4.setText(_translate("MainWindow", "Servo Angle:"))
        self.label_5.setText(_translate("MainWindow", "Battery:"))
        self.label_6.setText(_translate("MainWindow", "AutoPilot"))
        self.label_7.setText(_translate("MainWindow", "Cruise Control:"))
        self.label_8.setText(_translate("MainWindow", "Speed:"))
        self.cruise.setText(_translate("MainWindow", "On"))
        self.label_9.setText(_translate("MainWindow", "Collision Prevention:"))
        self.collision.setText(_translate("MainWindow", "On"))
        self.label_10.setText(_translate("MainWindow", "Lane Keeping:"))
        self.lane.setText(_translate("MainWindow", "On"))



